### ISSUE TITLE
Adminhtml url

### ISSUE THREAD

**Issue by newlite** [mailup/mailup-magento#1]
On the Magento 1.9.3.3 in the file app/design/adminhtml/default/default/template/mailup/mailupsync/sysconfigjavascript.phtml

Code
`urlTest = '<?php echo Mage::getModel('adminhtml/url')->getUrl("mailup/adminhtml_configuration/testconnection");`
is generated incorrect URL path.

The issue was fixed by creating a custom helper for generating correct admin URL and rewriting this sysconfigjavascript.phtml template file.

So my question: Is it this issue related to new Magento version or this is only on my client website (There are a lot of extensions and core rewrites).

Thanks!

**Comment by giuseppemorelli** [comment]
Hello @newlite,
actually we are working to update the extension with the last security patches and version.
Current version (2.7.4) is supported with magento until 1.9.2.4.
So, yes maybe your Magento version is not supported yet.

We will make some deeply test with your issue.

**Comment by giuseppemorelli** [comment]
Hello @newlite,
we have just released a new version (2.7.5).
We thing that your problem will be solved with this release.

Please, don't hesitate to comment if you have some problems.
Thank you!
