### ISSUE TITLE
Errore salvataggio Configurazione

### ISSUE THREAD

**Issue by alessandro-magi** [mailup/mailup-magento#2]
Salve, ho problemi con il plugin di Mailup, l'ho appena aggiornato alla ultima versione, ma non risolve il problema.

Tutte le volte che salvo la configurazione del plugin di Mailup, mi resistituisce l'errore:

"Error in console URL"

La nostra url admin è:  *.mailupclient.com

E' possibile risolvere questo errore?
Purtroppo non mi permette il regolare funzionamento di un'altra estensione, quella della PWS per far comunicare magento con Eprice.

Cordiali Saluti

![errore-console-url](https://user-images.githubusercontent.com/22619013/27838034-4e9d9a38-60e8-11e7-97c5-739eaa06ebc7.jpg)

**Comment by alessandro-magi** [comment]
Mi sono appena accorto che dagli altri due store Magento, la console funziona regolarmente. Gli altri due store sono gestiti con la versione 1.9.2.4, mentre quello per il quale continua a darmi l'errore, utilizza la versione 1.7.0.2.

**Comment by giuseppemorelli** [comment]
Salve,
è stata rilasciata la nuova release 2.7.5.
Questa release risolve i problemi con l'ultima patch di magento (SUPEE-6788)
In quali di questi store è presente tale patch?

Un test che si può fare è abilitare il log di Magento (Sistema > Configurazione > Sviluppatore) e lanciare un test di connessione. Fatto ciò andare sotto la /var/log/system.log e cercare la stringa "Testing Connection - console". In tale scritta viene scritto il dettaglio errore.

Eventualmente ce lo può scrivere come commento alla issue.
Grazie mille

**Comment by alessandro-magi** [comment]
Salve, la patch è stata applicata nei due siti con Magento 1.9.2.4, mentre su Magento 1.7.0.2 non è stata applicata, non è che può derivare da questo?

Ho attivato i log e ho verificato se ci fosse la stringa "Testing Connection - console", appena effettuavo un test di connessione. Purtroppo non è presente.

Ci sono altri controlli che posso eseguire?

Cordiali Saluti

**Comment by alessandro-magi** [comment]
Ho scaricato e installato l'aggiornamento, purtroppo però non risolve il problema.

**Comment by giuseppemorelli** [comment]
Per "tamponare" il blocco nel salvataggio, può modificare la classe **MailUp_MailUpSync_Helper_Data** modificando la funzione _testConnectionConsole() in questo modo:

```
protected function _testConnectionConsole($urlConsole)
{
      // temp edit
       return true;
        .......
}
```

Stiamo implementando una nuova feature per non bloccare il salvataggio nel backend.

**Attenzione!** La modifica è temporanea e non deve essere permanente. Va tolta non appena rilasceremo la nuova versione.

**Comment by alessandro-magi** [comment]
Ho applicato la modifica, ora non mi segnala più quell'errore.

Attendo che venga rilasciato il nuovo aggiornamento.

Grazie

**Comment by giuseppemorelli** [comment]
Salve @cacio88,
stiamo per rilasciare una nuova release con l'opzione per lo skip del controllo url.
Se vuole provare un'anteprima della release può scaricarla a questo link: https://github.com/mailup/mailup-magento/archive/release/2.7.6.zip

La release aggiunge anche un'ottimizzazione nel salvataggio della configurazione backend che evita il "blocco" di altre estensioni.

Anche dopo il rilascio ufficiale, è bene prima testare l'estensione in un ambiente di staging.

**Comment by alessandro-magi** [comment]
Salve, ho avuto la possibilità di testare l'estensione e la funzione di skip della url funziona benissimo.

Grazie

**Comment by giuseppemorelli** [comment]
Salve,
è stata rilasciata la nuova versione del plugin: https://github.com/mailup/mailup-magento/releases/tag/2.7.6

Per eventuali info, problemi può aprire una nuova issue specificando il problema.

Grazie mille
