### ISSUE TITLE
PROBLEMA CARRELLO ABBANDONATO

### ISSUE THREAD

**Issue by CAPITANSPORT** [mailup/mailup-magento#3]
Dopo tantissimi problemi legati alla mancata installazione del plugin sul nostro ambiente di staging, ancora non riusciamo a tracciare i dati del "carrello abbandonato" e "ultimo ordine".
Il plug in da voi fornito su magento connect non poteva essere installato perchè incompatibile con la nostra versione di Magento  1.9.2.1 e per questo motivo, il nostro supporto tecnico ha dovuto effettuare altre operazioni.
Ecco la modifica che hanno apportato:
- scaricare lo zip del modulo dal sito di magento connect (c'è una way-around per scaricarlo avendo la key del modulo), portarlo sui nostri ambienti, tracciarlo sotto versioning e poi deployarlo dapprima in staging e poi in produzione
La versione di PHP sull'ambiente di staging è la 5.6.30.

Allego:
[mail up log.docx](https://github.com/mailup/mailup-magento/files/1142761/mail.up.log.docx)
![configurazione 1](https://user-images.githubusercontent.com/30124499/28130077-0679f126-6736-11e7-924c-fc46f52b9993.png)
![configurazione 2](https://user-images.githubusercontent.com/30124499/28130076-06768950-6736-11e7-923f-b1e167e50266.png)

So che ci sono degli aggiornamenti del plugin, ma onestamente dopo tanti mesi di tentativi a vuoto, vorrei avere delle risposte certe.

Grazie,
Domenico

**Comment by giuseppemorelli** [comment]
Salve,
purtroppo i tempi nel magento connect sono più lunghi e stiamo effettuando un passaggio graduale verso github.
Il download dell'ultima versione al momento è disponibile solo in questa piattaforma (e non sul connect): [https://github.com/mailup/mailup-magento/releases](https://github.com/mailup/mailup-magento/releases) e può essere scaricato con link diretto, con composer e tramite modman.

Riguardo al problema segnalato:
1) vorremmo capire se sono abilitati i carrelli persistenti dentro magento. Andare su System > Configuration > Customers > Persistent Shopping Cart
2) (non diretto al problema segnalato ma da sistemare) setting del mapping dei campi: il campo fax di Mailup è associato sia a Fax di magento che Sesso di magento

Può farci sapere riguardo il punto 1?
Fatto ciò proseguiamo con tutti gli altri controlli.
Grazie mille

**Comment by CAPITANSPORT** [comment]
Salve giuseppe,
per quanto riguarda l'aggiornamento, ci consigli di farlo? All'interno non abbiamo molte competenze informatiche quindi mi sa che nel caso, dovremmo far fare una valutazione alla nostra web agency.
Ti rispondo subito:

1. i carrelli non erano abilitati! Ho provveduto ad abilitare la funzione. Di seguito trovi uno screen dei settaggi
![carrello persistente magento](https://user-images.githubusercontent.com/30124499/28178420-aebfb91a-67fe-11e7-96bb-c668806fb3f3.png)
2. ho tolto il campo fax associato a sesso, ma non mi risulta una campo "genere" o "sesso" nel menu a tendina

Ora faccio degli ordini test per vedere se traccia il carrello abbandonato?

Grazie per la rapida risposta

**Comment by giuseppemorelli** [comment]
Salve,
sicuramente con l'aggiornamento non avrete problemi per quanto riguarda le nuove patch di sicurezza (è stato testato fino alle 1.9.3.3).
Al momento però non può farlo tramite il magento connect, quindi è necessario un intervento tecnico.
Per quanto riguarda le operazioni:
1) il settaggio purtroppo non è retroattivo, quindi è necessario attendere che si "formino" i carrelli abbandonati
2) il campo "sesso" è presente in mailup ma in magento di base non esiste a meno che non venga implementato con una personalizzazione. Può lasciarlo "vuoto" per il momento.

Con gli ordini di test può tracciare il totale ordinato e tutto ciò che riguarda l'anagrafica cliente (città, provincia).
Come scritto sopra, per i carrelli abbandonati bisogna attendere un po'. Per iniziare il test può loggarsi nel sito con la sua user e password, mettere qualche prodotto nel carrello e chiudere il browser (in questo modo ha creato il suo carrello abbandonato).
Il test di sync può farlo fra qualche giorno.

**Comment by CAPITANSPORT** [comment]
Ok, allora per il momento direi di rimandare l'aggiornamento.

1. ok, farò dei test per verificarne il corretto funzionamento
2. ok, lo lascerò vuoto., anche perchè per il momento non è una nostra priorità

Ti terrò aggiornato, intanto grazie per la disponibilità e sopratutto per la chiarezza!

**Comment by CAPITANSPORT** [comment]
Nella giornata di ieri ho fatto dei test, ma su mailup ancora non vengono tracciati i dati del carrello abbandonato.

Ecco alcuni screenshot:
![screenshot 2017-07-15 09 42 42](https://user-images.githubusercontent.com/30124499/28237543-408ecc5c-6942-11e7-91a1-4a11dd16084b.png)
![screenshot 2017-07-15 09 42 50](https://user-images.githubusercontent.com/30124499/28237548-4dec5856-6942-11e7-9a79-9893d0e1d652.png)

**Comment by giuseppemorelli** [comment]
Salve,
giusto un controllo lato magento per sicurezza.
Nella sezione: Report > Carrello > Carrelli abbandonati     cosa trova?
Può mandare uno screenshoot di quella sezione?
Grazie mille

**Comment by CAPITANSPORT** [comment]
Salve, 
purtroppo trovo un solo carrello abbandonato datato 2014 (all'epoca dei primi test).
Ecco uno screenshot
![screenshot 2017-07-17 09 14 34](https://user-images.githubusercontent.com/30124499/28258317-ed57fa96-6ad0-11e7-959e-e0aed257efc3.png)

Sembrerebbe che il problema sia in magento ... che mi consiglia di fare?

**Comment by giuseppemorelli** [comment]
Salve,
ulteriori controlli possibili che si possono fare sono:
- sistema > configurazione > VENDITE > checkout  (sezione "carrello"): verificare "Durata dichiarata (giorni)" -> deve essere maggiore di zero
- il cronjob di magento è attivo?

Purtroppo se i dati non sono presenti nella lista dei carrelli abbandonati di magento, lato mailup non si può fare più di tanto.

**Comment by CAPITANSPORT** [comment]
Salve ,

1. anche se il percorso è stato sistema > configurazione > VENDITE > modulo pagamento - carrello, sembra tutto ok. Ecco uno screen
![screenshot 2017-07-18 16 03 26](https://user-images.githubusercontent.com/30124499/28321573-dbb89044-6bd3-11e7-8241-b421fbf3cccd.png)

2. il cronjob dovrebbe essere attivo (la nostra web agency tempo fa ci aveva detto che lo fosse). C'è un modo per verificarlo?

A questo punto, abbiamo fatto tutte le verifiche? Il problema allora deve essere in magento.

**Comment by CAPITANSPORT** [comment]
Ho appena provato a testare il carrello abbandonato in produzione, abilitando il "carrello persistente" è credo funzioni, perchè in report - carrello - carrelli abbandonati, risulta il mio test. Ecco uno screenshot
![screenshot 2017-07-18 16 55 37](https://user-images.githubusercontent.com/30124499/28323768-ffb8b360-6bd9-11e7-980c-9b2ed1ecf3a1.png)

A questo penso sia un problema nell'ambiente di staging.

Portando il tutto in produzione non dovrebbero esserci problemi. 
Mi consiglia di portare in produzione il modulo con la stessa procedura utilizzata per l'ambiente di staging, o meglio fare l'installazione tramite link diretto https://github.com/mailup/mailup-magento/releases con composer e tramite modman?

**Comment by giuseppemorelli** [comment]
Salve,
riguardo ai punti scritti:
1 - probabilmente si hanno traduzioni differenti
2 - dovrebbe controllare i cronjob impostati nel sistema operativo (da terminale o pannello)

Non ho informazioni riguardo alla struttura e configurazione del progetto nel server di produzione, in generale dovrebbe scaricare tutto in locale (manuale o con composer), caricare su un repository git e scaricarlo nel server di produzione (ogni progetto/azienda ha un suo sistema per fare il deploy).
Sulla procedura di deploy, se non si hanno competenze tecniche, è bene affidarsi all'azienda che gestisce il sito.
