### ISSUE TITLE
Cannot save the config

### ISSUE THREAD

**Issue by juandiegojr** [mailup/mailup-magento#4]
Hello and thanks for the module,

Sorry if I write you in english, I'm from Spain.
I'm trying to test this module, also add url, user and password and Test Connection tells me everything is OK.

But when I try to save the config in any scoope of my system it reloads the page and show the config fields empty with the message:

MailUp configuration is not complete

I'm using magento 1.9.2.4

Thanks!

**Comment by giuseppemorelli** [comment]
Hello @juandiegojr,
no problem about the language, we prefer english so anyone in the world can read the issue (maybe is not only your problem).
We are working to create a new system for testing the console url and the configuration in general.
For the moment follow these steps:
1) add url, use and password
2) save config
3) try test connection -> now you can view "List and Default Group from MailUp"
4) save again

Please after that send us a feedback.
Thank you!

**Comment by juandiegojr** [comment]
Thanks Giuseppe,

Just tried the steps as follow and the problem persists,
Added URL, user and password + save config (without testing) and the fields when to blank with the message MailUp configuration is not complete:
![image](https://user-images.githubusercontent.com/16169562/28773437-d0fb8dee-75e9-11e7-8b4a-4b292f4c2046.png)

Thanks

**Comment by juandiegojr** [comment]
Just a thouhg,

My magento installation is using a custom table prefix, could be this?

**Comment by giuseppemorelli** [comment]
Hello @juandiegojr,
if in your procedure do not receive any errors or success message I think you are using a wrong user and/or password (Web Service Username | Web service Password).
Web Service Username is different from MailUp console username.

Follow this guide: http://help.mailup.com/display/mailupUserGuide/Magento+Extension%3A+Settings
paragraph "Configuration details".

```
Your MailUp API User Name (part of your MailUp Web Services API credentials ). To retrieve your MailUp API user name and password, log into your MailUp admin console and navigate to Settings > Account settings > Developer's corner > Web Services.
```

We will write a complete guide in the future here in github (wiki section).
Please, let me know if everything is ok.

**Comment by juandiegojr** [comment]
Thanks Guiseppe!

Solved! :) That was my problem, I was using the login credentials and not the API user. My fault.
Also had to disable the IP verification and now my list are synced.

Regards

**Comment by giuseppemorelli** [comment]
You're welcome @juandiegojr!
Let me know if you need more informations.
