### ISSUE TITLE
Impossibile salvare configurazione

### ISSUE THREAD

**Issue by internetsm** [mailup/mailup-magento#5]
Buongiorno,

abbiamo riscontrato un problema con il plugin di Mailup per Magento.
Quando si effettua il salvataggio, tutti gli input vengono svuotati.

La versione del plugin è la **2.7.5**.
La versione di Magento è la **1.9.3.3**.

Come possiamo risolvere il problema?

Grazie mille, 
buona giornata.

**Comment by giuseppemorelli** [comment]
Salve,
il problema segnalato potrebbe essere identico alla issue #4 
Per favore, segua prima la procedura indicata in tale issue ed eventualmente ci segnali se il tutto è andato buon fine o meno.

Grazie
