### ISSUE TITLE
non riesco ad importare la data di nascita

### ISSUE THREAD

**Issue by AndreaGaetanoGatti** [mailup/mailup-magento#6]
Buongiorno,

sono stato indirizzato da lei
![screenshot1](https://user-images.githubusercontent.com/30593113/28773922-bcc1fdca-75eb-11e7-983f-d492dedb0bca.png)
![screenshot2](https://user-images.githubusercontent.com/30593113/28773933-c7744e6c-75eb-11e7-8364-087fc38222a1.png)
![screenshot3](https://user-images.githubusercontent.com/30593113/28773943-cd6afc62-75eb-11e7-9d4b-48a71b5b8cc2.png)
![screenshot4](https://user-images.githubusercontent.com/30593113/28773949-d128956c-75eb-11e7-848d-a90f93eb907b.png)
![screenshot5](https://user-images.githubusercontent.com/30593113/28773952-d4eb01d0-75eb-11e7-9ae9-9dfa3800030e.png)

 dal servizio clienti MailUp. Volendo creare una newsletter automatica di “buon compleanno”, il 20 luglio scorso ho aggiunto il campo anagrafico “DateOfBirth” in Configurazioni > Gestione piattaforma > Campi anagrafici (vedi screenshot1).
Al contempo sono andato sul back office del mio sito (Magento 1.9.0.1 con plugin MailUp versione 2.7.1 stable) in Newsletter > MailUp > Settings & Field Mapping ed ho collegato il campo appena creato (vedi screenshot2).
Oggi ho provato ad esportare i campi “Email” e “DateOfBirth” dal gruppo “Magento” della “Lista Italiano” ma purtroppo il campo “DateOfBirth” non è stato popolato (vedi screenshot3, screeshot4 e screenshot5).

In che cosa ho sbagliato? La ringrazio per un aiuto.

Ing. Andrea Gaetano Gatti
www.wineshop.it

**Comment by giuseppemorelli** [comment]
Salve Andrea,
proviamo a fare un test.
Crei un file `test.php` nella cartella dove si trova magento (la stessa dove c'è index.php) con il seguente contenuto:

```
<?php
define('MAGENTO', realpath(dirname(__FILE__)));
require_once(MAGENTO.'/app/Mage.php');

Mage::app();

$customer = Mage::getModel('customer/customer')
                ->setWebsiteId(1)
                ->loadByEmail('ag.gatti@gmail.com');

echo "CUSTOMER NAME: ".$customer->getName();
echo "<br />";
echo "CUSTOMER DATE OF BIRTH: ".$customer->getDob();
```

Da browser poi apra il file (www.sito.com/test.php). L'ouput deve essere di questo tipo:

```
CUSTOMER NAME: Andrea Gaetano
CUSTOMER DATE OF BIRTH: 1962-04-14
```

In base al test procediamo con gli altri controlli.
Grazie mille

**Comment by AndreaGaetanoGatti** [comment]
Buongiorno Giuseppe,

 

riesce a girarmi lei il file di test in modo che debba soltanto caricarlo nella directory?

 

La ringrazio molto del suo aiuto

**Comment by giuseppemorelli** [comment]
Salve Andrea,
qui il link per scaricare il file di test: https://www.dropbox.com/s/bbsc626fsk8msfi/test.php?dl=0

**Comment by AndreaGaetanoGatti** [comment]
Caricato: https://www.wineshop.it/test.php

E funziona :-)

**Comment by giuseppemorelli** [comment]
Salve Andrea,
avrei bisogno di 4 screenshoot del backend di magento:
- newsletter > mailup > settings & field mapping
- newsletter > mailup > view mailup tasks
- newsletter > mailup > view task data
- newsletter > mailup > view logs

Inoltre dovrebbe controllare se è attivo il cronjob di magento (file cron.php sotto "schedulatore" nel suo hosting).

**Comment by AndreaGaetanoGatti** [comment]
Buonasera Giuseppe, in allegato gli screenshot richiesti.

 

Andrea, per favore puoi verificare se è attivo il cronjob di magento (vedi sotto) e confermarlo a Giuseppe? Grazie

 

Ing. Andrea Gaetano Gatti

www.wineshop.it

**Comment by giuseppemorelli** [comment]
Salve Andrea,
purtroppo non è possibile inserire immagini alla issue tramite email.
E' necessario collegarsi in github ed inserire la risposta direttamente da li.
Gli allegati non sono stati caricati.

Può provare direttamente da web?
Grazie mille

**Comment by AndreaGaetanoGatti** [comment]
Buongiorno Giuseppe,

 

le ho girato gli allegati via github.

Le confermo che il cronjob di magento è sempre stato attivo.

 

Attendo sue indicazioni, grazie

 

Ing. Andrea Gaetano Gatti

www.wineshop.it

 

 

Da: Giuseppe Morelli [mailto:notifications@github.com] 
Inviato: martedì 1 agosto 2017 19:06
A: mailup/mailup-magento
Cc: AndreaGaetanoGatti; Author
Oggetto: Re: [mailup/mailup-magento] non riesco ad importare la data di nascita (#6)

 

Salve Andrea,
purtroppo non è possibile inserire immagini alla issue tramite email.
E' necessario collegarsi in github ed inserire la risposta direttamente da li.
Gli allegati non sono stati caricati.

Può provare direttamente da web?
Grazie mille

**Comment by giuseppemorelli** [comment]
Salve Andrea,
non trovo le immagini nella issue.
Come scritto in precedenza, dovrebbe rispondere alla issue loggandosi su github.com ed allegando le immagini.
Purtroppo con la risposta via email gli allegati vengono "persi".

**Comment by AndreaGaetanoGatti** [comment]
ecco le immagini

![screenshot4](https://user-images.githubusercontent.com/30593113/28976836-d3cd64f8-793f-11e7-8625-a6e2efecda52.png)

![screenshot3](https://user-images.githubusercontent.com/30593113/28976833-cf991f26-793f-11e7-905b-57f3d29c280c.png)

![screenshot3](https://user-images.githubusercontent.com/30593113/28976825-ca778da2-793f-11e7-8dde-cd82eb9929ca.png)

![screenshot2](https://user-images.githubusercontent.com/30593113/28976813-c21cb4de-793f-11e7-81e9-763af46b2ea7.png)

![screenshot1](https://user-images.githubusercontent.com/30593113/28976804-b8f591c8-793f-11e7-912f-31ae694f62db.png)

**Comment by AndreaGaetanoGatti** [comment]
Ora dovrebbero esserci, grazie

**Comment by AndreaGaetanoGatti** [comment]
Ora dovrei averle caricate, le ha ricevute? Grazie

**Comment by giuseppemorelli** [comment]
Salve @AndreaGaetanoGatti,
ho ricevuto tutte le immagini.
Dopo aver effettuato un controllo con l'assistenza MailUp della sua console è stato riscontrato che alcuni utenti hanno la data di nascita valorizzata nella console.
(per motivi di privacy non posso pubblicare gli indirizzi email qui su github, se vuole l'elenco è necessario contattare direttamente l'assistenza MailUp indicando la issue 6 di github)

Il problema dunque è legato ad alcuni utenti già presenti in MailUp dove è stata aggiornata successivamente la data ma non nei seguenti eventi:
- iscrizione/cancellazione da newsletter
- completamento di un ordine
Se si modifica la sola data di nascita da backend magento (sezione clienti), il dato non viene inviato a mailup. 
Può "forzare" l'operazione eseguendo un sync tramite l'operazione "Sincronizza/segmenta clienti" dentro Magento.

Infine, la sua versione dell'estensione MailUp per magento andrebbe aggiornata quantomeno alla 2.7.2 oppure all'ultima disponibile 2.7.5.
In questo modo ha una versione che risolve molti problemi riguardo lo scambio dati fra le piattaforme.

Prima di proseguire con altri test/verifiche è necessario che aggiorni (prima in un ambiente di test) la versione dell'estensione Magento.
Grazie mille

**Comment by AndreaGaetanoGatti** [comment]
Grazie Giuseppe delle informazioni,
ho provato ad esportare, da console MailUp, il campo email ed il campo DateOfBirth del gruppo Magento della Lista Italiano, e mi risultano soltanto 17 indirizzi (su 6385!) popolati con la data di nascita.

Mi ero scordato di dirle che la data di nascita dei clienti era stata importata, nel database di Magento, dal precedente sito di e-commerce, circa 2 anni e mezzo fa, quando erano stati importati tutti gli account dei clienti presenti sul vecchio sito.

Sull’attuale sito in Magento non viene richiesta la data di nascita per cui i nuovi account non riportano questa informazione. Inoltre le date di nascita (ove presenti) non sono modificabili dai clienti in quanto non vengono visualizzate, così pure non sono state mai da noi modificate sul backend di Magento.

Detto ciò, so per certo, per verifica diretta, che ci sono tanti vecchi account (come i miei: ag.gatti@wineshop.it, ag.gatti@gmail.com e ag.gatti@libero.it) che hanno il campo data di nascita popolato ma il dato, purtroppo, non è stato sincronizzato su MaiUp.

A questo proposito, sarebbe così gentile da spiegarmi punto per punto come faccio a "forzare l'operazione eseguendo un sync tramite l'operazione "Sincronizza/segmenta clienti" dentro Magento?

Magari, così facendo, si popola il database su MailUp con le date di nascita mancanti …

grazie mille per l’aiuto

Ing. Andrea Gaetano Gatti

www.wineshop.it

**Comment by giuseppemorelli** [comment]
Salve @AndreaGaetanoGatti,
per l'utilizzo specifico dell'estensione (guide ecc...) dovrebbe contattare il supporto diretto di MailUp in quanto potrebbero essere inviati dati "sensibili" relativi alla propria piattaforma (indichi sempre che ha una issue su github).
Il supporto su github è per verificare se ci sono errori sul codice dell'estensione Magento.

In ogni caso: c'è video-guida che spiega il funzionamento della segmentazione: https://www.youtube.com/watch?v=9zroTs0vv5k

Se, dopo aver fatto una sincronizzazione tramite segmentazione, non dovesse avere i dati aggiornati è più che necessario l'aggiornamento dell'estensione.
Grazie mille
